### ISSUE TITLE
mobile: "Menu" different to language menu

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool-website-2018#14]
Clicking "menu" open a nice mobile-ready menu, clicking the language menu opens the same menu as on desktop. Couldn't the mobile menu be used here, too?

**Comment by neprev** [comment]
@danielnaber please check

**Comment by danielnaber** [comment]
This(?) broke the close button: https://screenshots.firefox.com/09lQoclck4wa5unq/127.0.0.1

**Comment by neprev** [comment]
@danielnaber yeah sorry, fixed. Please check. If now the site is on production, should we create a dev branch?

**Comment by danielnaber** [comment]
Either that or we don't break stuff :-)
