### ISSUE TITLE
better mobile usability

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool-website-2018#16]
- [ ] The keyboard is in the way on mobile screens when clicking on an error. See what spellboy.com does to solve this and implement it, too.
- [ ] The Check button should not be covered by the keyboard - spellboy.com has solved this, too, the check button moves as soon as the keyboard appears.
- [ ] The question mark icons in the pricing table don't work well, it's difficult to tap them, can this be improved? (Or is this solved with a larger font?)

**Comment by neprev** [comment]
@danielnaber 

1 - they also have a keyboard appear

<img width="453" alt="screen shot 2018-04-30 at 03 13 33" src="https://user-images.githubusercontent.com/28347933/39411084-be817432-4c24-11e8-9c90-09a6131eb3bc.png">

2 - they have only one editor on the screen, so the document's height coincides with the height of the editor. In this case, you can put buttons as fixed on the bottom position of the document. We can not do this. I'll figure out if there's anything to be done here.

3 - If we here increase the size of the icons without changing the text size, this will break line heights.

<img width="376" alt="screen shot 2018-04-30 at 03 13 50" src="https://user-images.githubusercontent.com/28347933/39411127-a92290e8-4c25-11e8-8598-a11aa16029bf.png">

We can do something like this

<img width="379" alt="screen shot 2018-04-30 at 03 26 16" src="https://user-images.githubusercontent.com/28347933/39411161-4d8878fa-4c26-11e8-93e8-350618a5d933.png">

**Comment by danielnaber** [comment]
> I'll figure out if there's anything to be done here.

Thanks for the analysis. Yes, please see if there's a way to get to a similar behavior with the buttons.
