### ISSUE TITLE
iphone 7: error popup is incomplete / cut off

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool-website-2018#18]

**Comment by neprev** [comment]
@danielnaber I didn't understand. Can you describe the task in more detail or may be attach a screenshot?

**Comment by danielnaber** [comment]
![iphone-languagetool_org](https://user-images.githubusercontent.com/857004/39295653-3adfa05a-493f-11e8-8308-8e838be54648.jpg)

**Comment by neprev** [comment]
@danielnaber please check `18-examples-fix` branch. Should be fixed.
