### ISSUE TITLE
Visual fixes

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool-website-2018#19]
@neprev This is feedback from Elena. When she says something should be different, she usually refers to the design at zeplin. Ask me in the upwork chat or here if something is not clear.

1. The space between the logo and text has to be bigger
2. The design of the window that drops down has to different (please, check zeplin)
3. The arrows have to be different
4. ~~We have to change the color of Premium Upgrade button~~
5. Please check hover effect
6. The quotations are cut off a bit + all the content has to be aligned
7. The space between the text "Pricing" and the content around has to be different
8. These icons have to be different
9. The arrow has to be different and the window that drops down as well
10. Hover effect
11. The shadow has to be different
12. To change the color of the text
13. Too much space
14. The screenshot is too small
15. The space between content is too small
16. The content has to be aligned
17. Too much space between "development team privacy contact"
18. Hover effect
19. The buttons have to have the same size + hover effect
20. All this block looks messy
21. This space has to be the same everywhere

![1](https://user-images.githubusercontent.com/857004/39093448-3b4b09e8-4620-11e8-8745-074fe7be0d6e.png)
![2](https://user-images.githubusercontent.com/857004/39093449-3b673596-4620-11e8-9041-d6be07463193.png)
![3](https://user-images.githubusercontent.com/857004/39093450-3b876ed8-4620-11e8-903f-96a7e386b3cd.png)
![4](https://user-images.githubusercontent.com/857004/39093451-3ba073d8-4620-11e8-8c26-a934fcdf9fd2.png)
![5](https://user-images.githubusercontent.com/857004/39093452-3bbf38cc-4620-11e8-94c0-317ed01e2b24.png)
![6](https://user-images.githubusercontent.com/857004/39093453-3bd91c42-4620-11e8-86d5-c149285781d3.png)
![7](https://user-images.githubusercontent.com/857004/39093454-3c05dfa2-4620-11e8-8e6c-37fc17bfa0da.png)
![8](https://user-images.githubusercontent.com/857004/39093455-3c316f28-4620-11e8-8236-6da8a4cb7eee.png)

**Comment by neprev** [comment]
@danielnaber 

2, 8 - these icons are not importable from Zeplin. Please provide them.
9 - Where i can find design of this dropdown. And here needs to do javascript because select dropdown are not customizable by css only.
17 - as in the design the links are stretched over the entire width of the container (just them here is less than in design)
20 - what should be done?

The rest is done, please check on `18-visual-fixes` branch

**Comment by danielnaber** [comment]
9 - under Zeplin, "LT 2" -> "languages" slide

**Comment by danielnaber** [comment]
the icons:



[icons.zip](https://github.com/languagetool-org/languagetool-website-2018/files/1954202/icons.zip)

**Comment by neprev** [comment]
@danielnaber 

> We need to consider that almost everything is translated (and thus text strings might be longer), so please always check with some sub pages.

Now i have removed the fixed width - the elements stretch the container. And when hovering (font becomes bold), dropdown jump in size.

About 9 - on the "languages" slide on Zeplin there is no this dropdown. Do you mean to make it same as dropdown in the header? (we also have the dropdowns in the editor and they are differ in design too)
Also I changed the icons, please check `18-visual-fixes`

**Comment by danielnaber** [comment]
About 9 - right, it's in "redesign main". I think only the arrow looks a bit different in the design. 

About language menu: please make it longer so that so scrollbar is needed, this way it should look better. Also, please remove the bold on hover to avoid the resizing (both language and add-on menu).

**Comment by neprev** [comment]
@danielnaber 

> About language menu: please make it longer so that so scrollbar is needed, this way it should look better. Also, please remove the bold on hover to avoid the resizing (both language and add-on menu).

Please check.

And what should i here? 

> 9. The arrow has to be different and  _**the window that drops down as well**_

**Comment by danielnaber** [comment]
> The arrow has to be different and the window that drops down as well

Let's skip that for now.
