### ISSUE TITLE
change colors

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool-website-2018#32]
See "main blue" and "blue 2" in zeplin

[background.svg.zip](https://github.com/languagetool-org/languagetool-website-2018/files/1960456/background.svg.zip)

**Comment by neprev** [comment]
@danielnaber please check on `32-change-colors`

**Comment by danielnaber** [comment]
Background slightly too light, make white on light background difficult to read:
![too-light](https://user-images.githubusercontent.com/857004/39491452-c12b5982-4d8c-11e8-8194-a784518696de.png)

No need for border around email:
![border](https://user-images.githubusercontent.com/857004/39491430-ac128e4e-4d8c-11e8-9b28-e2c8a522f355.png)

Also, have you started from the latest master? Because the behaviour of the "Premium Upgrade" button lacks my latest change.

**Comment by neprev** [comment]
@danielnaber I've created a branch before your commit, but now i've merged master here. I also changed the gradient to slightly darker. Please check

**Comment by danielnaber** [comment]
Colors are better now (although I'll still change them a bit myself), but border around email field is still there and doesn't look good.

**Comment by danielnaber** [comment]
Border around email field seems to be Firefox only - please always test in at least FF and Chrome.

**Comment by danielnaber** [comment]
(previous comments deleted, please ignore, I made a mistake)
