### ISSUE TITLE
Add description meta tag

### ISSUE THREAD

**Issue by janschreiber** [languagetool-org/languagetool-website-2018#34]
Currently languagetool.org appears like this in the Google search results:
![bild 1](https://user-images.githubusercontent.com/4381288/39674285-cb49fb74-5149-11e8-9d6a-39d3f9fd0380.png)
Below the link, some random text from the main page is displayed. Looks a little messy.
AFAIK, this can be easily remedied by adding the following line to the `<head>` section of the main page:
`<meta name="description" content="LanguageTool is ...">` . This is also a commonly used SEO technique.

**Comment by danielnaber** [comment]
Thanks, I've added that - Google has its own logic in whether it uses the description, though.
