### ISSUE TITLE
Changing language for grammar checking shows languages in random order

### ISSUE THREAD

**Issue by dpelle** [languagetool-org/languagetool-website-2018#40]
Clicking on the button to change the language for grammar checking on
LT's main page (https://languagetool.org/ ) shows a list of languages.
The languages seem layed out in random order. We should order them
alphabetically or else it's a bit hard to find the language user is interested in.

**Comment by dpelle** [comment]
Following screenshot shows how the list of language currently shows up:

![language-lt-random-order](https://user-images.githubusercontent.com/2261629/40233226-6a991848-5aa2-11e8-89b1-a1afdc96174e.png)

I was looking for Breton and I did not expect it to be in the middle.

**Comment by danielnaber** [comment]
Should be fixed now, only "auto-detect" is a special case.
