### ISSUE TITLE
Slider: part of the text is cut off

### ISSUE THREAD

**Issue by janschreiber** [languagetool-org/languagetool-website-2018#41]
In Firefox (Linux) with 1024 px screen width, part of the slider text is cut off on the right for me:
![2018-05-19-003338_1024x768_scrot](https://user-images.githubusercontent.com/4381288/40318637-8eab4ab4-5d25-11e8-8e54-ff8a3c6a0869.png)

**Comment by danielnaber** [comment]
Still cut off for me with very narrow browser window (e.g. mobile).

**Comment by neprev** [comment]
@danielnaber please check
