### ISSUE TITLE
wrong language detection 

### ISSUE THREAD

**Issue by kostyfisik** [languagetool-org/languagetool-website-2018#44]
Inserting "Масло масляное" in Russian lead to detection of English, which is wrong. In the meanwhile the russian error is correctly detected. 

![screenshot from 2018-07-22 14-14-01](https://user-images.githubusercontent.com/5239997/43045047-e630ed4c-8db9-11e8-9677-25885c576d66.png)

**Comment by danielnaber** [comment]
We use https://github.com/optimaize/language-detector in our core and it - like most ngram-based approaches - doesn't work well with short texts.

**Comment by Discostu36** [comment]
The problem seems to have disappeared 
![ru](https://user-images.githubusercontent.com/30999326/44532284-0cfd7100-a6f3-11e8-9481-23ef9fcb80de.PNG)

**Comment by danielnaber** [comment]
Yes, it should be much better now thanks to: https://forum.languagetool.org/t/improved-language-detection/3250
