### ISSUE TITLE
Language selection should use native names

### ISSUE THREAD

**Issue by Discostu36** [languagetool-org/languagetool-website-2018#45]
For the language selection on the website, the languages should be labeled with their native names ("English, Deutsch, Français"). Also, the menu item should stay in English ("Languages"). Otherwise, a user could get stuck on a version on the website where he can't find back to his mother tongue.

![language](https://user-images.githubusercontent.com/30999326/44568071-732ad800-a775-11e8-8d20-614df63a71f6.PNG)

**Comment by janschreiber** [comment]
I agree that this is a serious usability issue. Suppose a European user clicks "Arabic" or "Chinese" by accident.

**Comment by danielnaber** [comment]
Should be fixed now.
