### ISSUE TITLE
Grammar error in meta description

### ISSUE THREAD

**Issue by ssokolow** [languagetool-org/languagetool-website-2018#66]
There's a typo in the description meta tag which gets surfaced when things like Discord produce an oEmbed card.

![screenshot4](https://user-images.githubusercontent.com/46915/57187467-d82af600-6ede-11e9-9501-cbe83f1b86d0.png)

"software" is not a countable noun, so it should be either "is free proofreading software" or "is a free proofreading tool", not "is **a** free proofreading software"

**Comment by danielnaber** [comment]
Thanks, will be online with the next update.
