### ISSUE TITLE
languagetool.org is showing me ads for grammarly

### ISSUE THREAD

**Issue by bobergj** [languagetool-org/languagetool-website-2018#76]
I think this screenshot sums it up:
![languagetool-org-ad](https://user-images.githubusercontent.com/265631/72039869-feb0f480-32e9-11ea-91c4-b53659268a9f.png)

**Comment by danielnaber** [comment]
When exactly was that?

**Comment by bobergj** [comment]
9 Jan 2020 at 14:11 UTC+9 (Japan)

**Comment by danielnaber** [comment]
@bobergj Thanks. Could you zip the screenshot and attach it again? Github re-compresses it, which removes information.

**Comment by bobergj** [comment]
Sorry 1) I don't seem to have saved the original file 2) you are asking too much for what was originally just a friendly tip. Just fix your ad blocklist if you don't want to show that ad :)
